; Listless default JSON style. See docs/08-style-config.md.

Style Json (.json) Common
{
	StringColor => Green
	BeforeDelimiterColor => Blue
	Symbols => {}[],:
	Strings => "
	Escape => \
	BeforeDelimiter => :
	CaseSensitive => On

	Reserved => false
	Reserved => null
	Reserved => true
}
